export {default as Home } from "./Home"
export {default as Page404 } from "./Page404"
export {default as Customers } from "./Customers"
export {default as Solutions } from "./Solutions"
export {default as Products_Technologies } from "./Products_Technologies"
export {default as Compuny } from "./Compuny"
export {default as Careers } from "./Careers"
export {default as Resources } from "./Resources"